/**
 * XUIRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateGatewayRequest
 */
class CreateGatewayRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.realm = this.constructor.getValue(obj.realm);
        this.username = this.constructor.getValue(obj.username);
        this.password = this.constructor.getValue(obj.password);
        this.description = this.constructor.getValue(obj.description);
        this.profileId = this.constructor.getValue(obj.profileId || obj.profile_id);
        this.register = this.constructor.getValue(obj.register);
        this.template = this.constructor.getValue(obj.template);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'realm', realName: 'realm' },
            { name: 'username', realName: 'username' },
            { name: 'password', realName: 'password' },
            { name: 'description', realName: 'description' },
            { name: 'profileId', realName: 'profile_id' },
            { name: 'register', realName: 'register' },
            { name: 'template', realName: 'template' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateGatewayRequest;
