/**
 * XUIRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateRouteRequest
 */
class CreateRouteRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.description = this.constructor.getValue(obj.description);
        this.prefix = this.constructor.getValue(obj.prefix);
        this.maxLength = this.constructor.getValue(obj.maxLength || obj.max_length);
        this.context = this.constructor.getValue(obj.context);
        this.destType = this.constructor.getValue(obj.destType || obj.dest_type);
        this.destUuid = this.constructor.getValue(obj.destUuid || obj.dest_uuid);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'description', realName: 'description' },
            { name: 'prefix', realName: 'prefix' },
            { name: 'maxLength', realName: 'max_length' },
            { name: 'context', realName: 'context' },
            { name: 'destType', realName: 'dest_type' },
            { name: 'destUuid', realName: 'dest_uuid' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateRouteRequest;
