/**
 * XUIRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateUser9001Request
 */
class CreateUser9001Request extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.extn = this.constructor.getValue(obj.extn);
        this.name = this.constructor.getValue(obj.name);
        this.password = this.constructor.getValue(obj.password);
        this.vmPassword = this.constructor.getValue(obj.vmPassword || obj.vm_password);
        this.context = this.constructor.getValue(obj.context);
        this.domain = this.constructor.getValue(obj.domain);
        this.cidName = this.constructor.getValue(obj.cidName || obj.cid_name);
        this.cidNumber = this.constructor.getValue(obj.cidNumber || obj.cid_number);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'extn', realName: 'extn' },
            { name: 'name', realName: 'name' },
            { name: 'password', realName: 'password' },
            { name: 'vmPassword', realName: 'vm_password' },
            { name: 'context', realName: 'context' },
            { name: 'domain', realName: 'domain' },
            { name: 'cidName', realName: 'cid_name' },
            { name: 'cidNumber', realName: 'cid_number' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateUser9001Request;
