/**
 * XUIRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const CreateRouteRequest = require('../lib/Models/CreateRouteRequest');
const ActionForMemberRequest = require('../lib/Models/ActionForMemberRequest');
const CreateGatewayRequest = require('../lib/Models/CreateGatewayRequest');
const KillGatewayRequest = require('../lib/Models/KillGatewayRequest');
const LoginRequest = require('../lib/Models/LoginRequest');
const DeleteRoom6001Request = require('../lib/Models/DeleteRoom6001Request');
const CreateUser9001Request = require('../lib/Models/CreateUser9001Request');
const CreateRoom6001Request = require('../lib/Models/CreateRoom6001Request');
const CreateConference7001AndInvite1014Request =
  require('../lib/Models/CreateConference7001AndInvite1014Request');

const classMap = {
    CreateRouteRequest,
    ActionForMemberRequest,
    CreateGatewayRequest,
    KillGatewayRequest,
    LoginRequest,
    DeleteRoom6001Request,
    CreateUser9001Request,
    CreateRoom6001Request,
    CreateConference7001AndInvite1014Request,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
